### ISSUE TITLE
Images for GitHub Pages site

### ISSUE THREAD

**Issue by amjibaly** [muslimhomeschoolnetwork/muslimhomeschoolnetwork.github.io#7]
![mhn_logo](https://cloud.githubusercontent.com/assets/61224/3424279/1e88b0fa-ffc8-11e3-8654-28e7aa2d83a5.jpg)

**Comment by syamout** [comment]
![organizational workshop](https://cloud.githubusercontent.com/assets/7043355/9429728/e975543c-498f-11e5-9a97-8d45d67fed45.jpg)

**Comment by syamout** [comment]
![getorganized](https://cloud.githubusercontent.com/assets/7043355/9429765/36a24c32-4991-11e5-8eac-432f87f35441.jpg)

**Comment by syamout** [comment]
![getorganized](https://cloud.githubusercontent.com/assets/7043355/9429767/4031985c-4991-11e5-935f-6b6aff826abc.jpg)

**Comment by syamout** [comment]
![organicdates](https://cloud.githubusercontent.com/assets/7043355/15100321/5aa605ca-1523-11e6-9e02-2ad46f16ef33.jpg)

**Comment by syamout** [comment]
![dates](https://cloud.githubusercontent.com/assets/7043355/15100353/11a8255a-1524-11e6-9dee-8fed45355ce6.JPG)

**Comment by syamout** [comment]
![datebox](https://cloud.githubusercontent.com/assets/7043355/15100356/27dd8be4-1524-11e6-8416-ef3797b40d3e.JPG)

**Comment by syamout** [comment]
![juliebogart](https://cloud.githubusercontent.com/assets/7043355/20945108/ca6e42da-bbba-11e6-94c1-d62b4e0bb8cd.jpg)

**Comment by syamout** [comment]
![braveschooling with julie bogart 2](https://cloud.githubusercontent.com/assets/7043355/20945150/f5c177f4-bbba-11e6-9c6c-66a0b3975551.jpeg)

**Comment by syamout** [comment]
![poetrytime](https://cloud.githubusercontent.com/assets/7043355/20945175/16b33556-bbbb-11e6-9d98-f77ba4acaabf.jpg)

**Comment by syamout** [comment]
![map](https://cloud.githubusercontent.com/assets/7043355/20945194/234a9f8e-bbbb-11e6-82c4-0f2c75e15587.jpg)

**Comment by syamout** [comment]
![braveschooling](https://cloud.githubusercontent.com/assets/7043355/20951231/76c2f18e-bbd9-11e6-85e6-f29ef7831262.jpg)

**Comment by syamout** [comment]
![mhncoronoa](https://user-images.githubusercontent.com/7043355/77235216-33a2b880-6b71-11ea-8e6c-344232c2b24f.png)

**Comment by syamout** [comment]
![socialize](https://user-images.githubusercontent.com/7043355/77243416-fd902380-6bc6-11ea-8846-c1f9ac559b53.png)

**Comment by syamout** [comment]
![nature](https://user-images.githubusercontent.com/7043355/77243417-054fc800-6bc7-11ea-9bae-70c0e07ee6e9.png)

**Comment by syamout** [comment]
![ididnt](https://user-images.githubusercontent.com/7043355/77243420-0c76d600-6bc7-11ea-86b2-8823fe40a90e.png)

**Comment by syamout** [comment]
![covid19](https://user-images.githubusercontent.com/7043355/77243425-16003e00-6bc7-11ea-9bed-b3eecf114c26.png)

**Comment by syamout** [comment]
![quicktips](https://user-images.githubusercontent.com/7043355/77243429-1dbfe280-6bc7-11ea-98c5-f8659de9b432.png)
